apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: ca
        secret:
          secretName: ca-secret
      containers:
      - name: web
        lifecycle:
          postStart:
            exec:
              command: [
                "/bin/sh", 
                "-c", 
                "cp /etc/certs/ca/ca.crt /usr/local/share/ca-certificates/ && update-ca-certificates"]
        image: web
        imagePullPolicy: Never
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:80"
        - name: SERVICES__API__WEATHERFORECAST
          value: "https://api/WeatherForecast"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: "/etc/certs/ca"
          name: ca
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
